name: 'Distil_XLSR_5_Custom_Trans_Layer_AASIST_from_bestr4_CosineAnnealing_MSE_Cosine_w_o_aug'
model:
  teacher:
    name: 'W2V2_AASIST'
    teacher_module_paths:
      - 'LL'
      - 'out_layer'
      - 'ssl_model.model.encoder.layers.1.final_layer_norm'
      - 'ssl_model.model.encoder.layers.4.final_layer_norm'
      - 'ssl_model.model.encoder.layers.7.final_layer_norm'
      

    teacher_module_ios:
      - 'False:True'
      - 'False:True'
      - 'False:True'
      - 'False:True'
      - 'False:True'
      

    pretrained_path: '/datad/hungdx/Towards-Real-Time-Deepfake-Speech-Detection-in-Resource-Limited-Scenarios/runs/aasist_runs/XLSR_AASIST_RawBoost4/best_LA_epoch32_0.004826_99.6229.pt'

    is_parallel: True

  student:
    name: 'Distil_XLSR_N_Trans_Layer_AASIST'
    student_module_paths:
      - 'LL'
      - 'out_layer'
      - 'ssl_model.model.encoder.layers.0.final_layer_norm'
      - 'ssl_model.model.encoder.layers.2.final_layer_norm'
      - 'ssl_model.model.encoder.layers.4.final_layer_norm'
      
      
    student_module_ios:
      - 'False:True'
      - 'False:True'
      - 'False:True'
      - 'False:True'      
      - 'False:True'      

    kwargs:
      num_layers: 5 # 
      order: 'custom' # 'middle' for middle layers, 'first' for first layers, 'last' for last layers, "custom" for custom layers
      custom_order: [1, 2, 3, 4, 5] # 2, 3, 4, 5th layer

is_learning_rate_scheduler: True

learning_rate_scheduler:
  name: 'CosineAnnealingWarmRestarts'
  params:
    T_0: 2 # number of epochs for the first restart
    T_mult: 2 # factor to increase T_0 after each restart
    eta_min: 0.000001
    verbose: False

train:
  padding_size: 16000  # 1s for LA19_1s
  learning_rate: 0.00001
  weight_decay: 0.00001
  batch_size: 32
  num_epochs: 200
  num_workers: 4
  amp: True
  teacher: True 
  patience: 20
  alpha: 1
  seed: 1234
  freeze_ssl_num_epoch: 0 # 0 for no freeze
  dataset: 'LA19_1s'
  augment_mode: 'rawboost' # 'rawboost' for rawboost, 'audiomentations' for audiomentations
  algo: -1 # No augmentation
  student_resume: '' # Stateless training
  cross_entropy_loss_weight: [0.9, 0.1]
  is_kl_loss: False
  copy_weights: True # Copy weights from teacher to student
  wandb_project_name: 'iconip2024'
  model_to_save: 'iconip2024_runs'

criterion_weights: [1, 1, 1, 1, 1, 1]

criterions:

  - key: 'MSELoss'
    kwargs:
      student_module_path: 'ssl_model.model.encoder.layers.0.final_layer_norm'
      student_module_io: 'output'
      teacher_module_path: 'ssl_model.model.encoder.layers.1.final_layer_norm'
      teacher_module_io: 'output'
  
  - key: 'CosineLoss'
    kwargs:
      student_module_path: 'ssl_model.model.encoder.layers.0.final_layer_norm'
      student_module_io: 'output'
      teacher_module_path: 'ssl_model.model.encoder.layers.1.final_layer_norm'
      teacher_module_io: 'output'

  - key: 'MSELoss'
    kwargs:
      student_module_path: 'ssl_model.model.encoder.layers.2.final_layer_norm'
      student_module_io: 'output'
      teacher_module_path: 'ssl_model.model.encoder.layers.4.final_layer_norm'
      teacher_module_io: 'output'
  
  - key: 'CosineLoss'
    kwargs:
      student_module_path: 'ssl_model.model.encoder.layers.2.final_layer_norm'
      student_module_io: 'output'
      teacher_module_path: 'ssl_model.model.encoder.layers.4.final_layer_norm'
      teacher_module_io: 'output'

  - key: 'MSELoss'
    kwargs:
      student_module_path: 'ssl_model.model.encoder.layers.4.final_layer_norm'
      student_module_io: 'output'
      teacher_module_path: 'ssl_model.model.encoder.layers.7.final_layer_norm'
      teacher_module_io: 'output'
  
  - key: 'CosineLoss'
    kwargs:
      student_module_path: 'ssl_model.model.encoder.layers.4.final_layer_norm'
      student_module_io: 'output'
      teacher_module_path: 'ssl_model.model.encoder.layers.7.final_layer_norm'
      teacher_module_io: 'output'
  
 
  