name: 'W2V2BASE_AASISTL_DKDLoss_cnsl'
model:
  teacher:
    name: 'W2V2_AASIST'
    teacher_module_paths:
      - 'LL'
      - 'out_layer'
    teacher_module_ios:
      - 'False:True'
      - 'False:True'
    pretrained_path: '/nfs/datab/hungdx/KDW2V-AASISTL/supcon_jan22_longR3_epoch_43.pth'
    is_parallel: False

  student:
    name: 'SelfDistil_W2V2BASE_AASISTL'
    student_module_paths:
      - 'LL'
      - 'out_layer'
    student_module_ios:
      - 'False:True'
      - 'False:True'

is_learning_rate_scheduler: False


train:
  learning_rate: 0.000005
  weight_decay: 0.00001
  batch_size: 64
  num_epochs: 300
  num_workers: 4
  amp: True
  teacher: True
  patience: 30
  seed: 42
  freeze_ssl_num_epoch: 0 # 0 for no freeze
  dataset: 'supcon_jan22'
  augment_mode: 'rawboost' # 'rawboost' for rawboost, 'audiomentations' for audiomentations
  
  cross_entropy_loss_weight: [0.21, 0.79]
  

criterion_weights: [1]

criterions:

  - key: 'DKDLoss'
    kwargs:
      student_module_path: 'out_layer'
      student_module_io: 'output'
      teacher_module_path: 'out_layer'
      teacher_module_io: 'output'
      alpha: 1
      beta: 8
      T: 2

