name: 'W2V2BASE_AASISTL_DKDLoss_cnsl_audiomentations_5_lts_v1'
# run with rawboost 4
model:
  teacher:
    name: 'W2V2_NLL_Multi'
    teacher_module_paths:
      - 'LL'
      - 'backend'
    teacher_module_ios:
      - 'False:True'
      - 'False:True'
    pretrained_path: '/datad/hungdx/KDW2V-AASISTL/conf-5-linear-feb07-29-36-epoch46.pth'
    is_parallel: False

  student:
    name: 'SelfDistil_W2V2BASE_AASISTL'
    student_module_paths:
      - 'LL'
      - 'out_layer'
    student_module_ios:
      - 'False:True'
      - 'False:True'

is_learning_rate_scheduler: True

learning_rate_scheduler:
  name: 'CosineAnnealingWarmRestarts'
  params:
    T_0: 20
    T_mult: 1
    eta_min: 0.00000001
    verbose: True

train:

  learning_rate: 0.0000005
  weight_decay: 0.00001
  batch_size: 16
  num_epochs: 500
  num_workers: 4
  amp: True
  teacher: True
  patience: 30
  seed: 8192
  freeze_ssl_num_epoch: 0 # 0 for no freeze
  dataset: 'supcon_feb07'
  augment_mode: 'rawboost' # 'rawboost' for rawboost, 'audiomentations' for audiomentations
  algo: 4
  student_resume: '/datad/hungdx/KDW2V-AASISTL/models/W2V2BASE_AASISTL_DKDLoss_cnsl_audiomentations_4_v14/best_checkpoint_35.pth'
  mixup: False
  cross_entropy_loss_weight: [0.21, 0.79]
  

criterion_weights: [1]

criterions:

  - key: 'DKDLoss'
    kwargs:
      student_module_path: 'out_layer'
      student_module_io: 'output'
      teacher_module_path: 'backend'
      teacher_module_io: 'output'
      alpha: 1
      beta: 8
      T: 4