name: 'W2V2BASE_AASISTL_SelfKD_DISTLoss_KD_Cosine_Embedding_Teacher_lr_scheduler_CyclicLR'
model:
  teacher:
    name: 'W2V2_AASIST'
    teacher_module_paths:
      - 'LL'
      - 'out_layer'
    teacher_module_ios:
      - 'False:True'
      - 'False:True'

  student:
    name: 'SelfDistil_W2V2BASE_AASISTL'
    student_module_paths:
      - 'LL'
      - 'out_layer'
    student_module_ios:
      - 'False:True'
      - 'False:True'

self_kd_config:
  temperature: 3
  alpha: 0.1
  beta: 1e-6

is_learning_rate_scheduler: True

learning_rate_scheduler:
  name: 'CyclicLR'
  params:
    base_lr: 0.00001
    max_lr: 0.0003
    step_size_up: 8
    mode: 'exp_range'
    cycle_momentum: False
    gamma: 0.99994
    verbose: False

train:
  learning_rate: 0.00001
  weight_decay: 0.0001
  batch_size: 64
  num_epochs: 300
  num_workers: 4
  amp: True
  teacher: True
  patience: 30
  seed: 42


criterion_weights: [0.5, 1]

criterions:
  - key: 'CosineLoss'
    kwargs:
      student_module_path: 'LL'
      student_module_io: 'output'
      teacher_module_path: 'LL'
      teacher_module_io: 'output'

  - key: 'DISTLoss'
    kwargs:
      student_module_path: 'out_layer'
      student_module_io: 'output'
      teacher_module_path: 'out_layer'
      teacher_module_io: 'output'
      gamma: 0.45
      beta: 0.56
      tau: 3

