name: 'W2V2BASE_AASISTL_SelfKD_audiomentations_from_best_pretrained_DKDLoss_cnsl'
model:
  teacher:
    name: 'W2V2_AASIST'
    teacher_module_paths:
      - 'out_layer'
    teacher_module_ios:
      - 'True:True'
    pretrained_path: '/datab/hungdx/KDW2V-AASISTL/supcon_jan22_longR3_epoch_43.pth'
    is_parallel: False

  student:
    name: 'SelfDistil_W2V2BASE_AASISTL'
    student_module_paths:
      - 'out_layer'
    student_module_ios:
      - 'True:True'

is_learning_rate_scheduler: False

self_kd_config:
  temperature: 3
  alpha: 0.1
  beta: 1e-6
  hidden_rep_loss_weight: 0.5

train:
  learning_rate: 0.0000001
  weight_decay: 0.00001
  batch_size: 64
  num_epochs: 300
  num_workers: 4
  amp: True
  teacher: False
  patience: 30
  seed: 42
  freeze_ssl_num_epoch: 0 # 0 for no freeze
  dataset: 'supcon_jan22'
  augment_mode: 'audiomentations' # 'rawboost' for rawboost, 'audiomentations' for audiomentations
  alpha: 0.9
  cross_entropy_loss_weight: [0.21, 0.79]
  student_resume: '/datab/hungdx/KDW2V-AASISTL/models/W2V2BASE_AASISTL_DKDLoss_cnsl_audiomentations/best_checkpoint_78.pth'
  raytune: False
criterions:


