name: 'Distil_XLSR_8_Trans_Layer_Linear_DKDLoss_noaudioaug_b16_randomstart_MultiStepLR_feb07'
model:
  teacher:
    name: 'W2V2_NLL_Multi'
    teacher_module_paths:
      - 'LL'
      - 'backend'
    teacher_module_ios:
      - 'False:True'
      - 'False:True'
    pretrained_path: '/datad/hungdx/KDW2V-AASISTL/conf-5-linear-feb07-29-36-epoch46.pth'

    is_parallel: False

  student:
    name: 'Distil_XLSR_N_Trans_Layer_Linear'
    student_module_paths:
      - 'LL'
      - 'backend'
    student_module_ios:
      - 'False:True'
      - 'False:True'
    kwargs:
      num_layers: 8 # 6 for 6 transformer layers, 12 for 12 transformer layers

is_learning_rate_scheduler: True

learning_rate_scheduler:
  name: 'MultiStepLR'
  params:
    milestones: [40, 70]
    gamma: 0.2
    verbose: True

train:

  learning_rate: 0.00001
  weight_decay: 0.00001
  batch_size: 16
  num_epochs: 300
  num_workers: 4
  amp: True
  teacher: True
  patience: 30
  seed: 1215
  freeze_ssl_num_epoch: 0 # 0 for no freeze
  dataset: 'supcon_feb07'
  augment_mode: 'rawboost' # 'rawboost' for rawboost, 'audiomentations' for audiomentations
  algo: -1 # No augmentation
  student_resume: '' # Stateless training
  cross_entropy_loss_weight: [0.21, 0.79]
  is_kl_loss: False

  

criterion_weights: [1]

criterions:

  - key: 'DKDLoss'
    kwargs:
      student_module_path: 'backend'
      student_module_io: 'output'
      teacher_module_path: 'backend'
      teacher_module_io: 'output'
      alpha: 1
      beta: 8
      T: 4

  # - key: 'OCKDLoss'
  #   kwargs:
  #     at_pairs:
  #       pair1:
  #         teacher:
  #           io: 'output'
  #           path: 'ssl_model.model.encoder.layers.5.fc2'
  #         student:
  #           io: 'output'
  #           path: 'ssl_model.model.encoder.layers.1.fc2'
  #       pair2:
  #         teacher:
  #           io: 'output'
  #           path: 'ssl_model.model.encoder.layers.11.fc2'
  #         student:
  #           io: 'output'
  #           path: 'ssl_model.model.encoder.layers.3.fc2'
  #       pair3:
  #         teacher:
  #           io: 'output'
  #           path: 'ssl_model.model.encoder.layers.17.fc2'
  #         student:
  #           io: 'output'
  #           path: 'ssl_model.model.encoder.layers.5.fc2'
  #       pair4:
  #         teacher:
  #           io: 'output'
  #           path: 'ssl_model.model.encoder.layers.23.fc2'
  #         student:
  #           io: 'output'
  #           path: 'ssl_model.model.encoder.layers.7.fc2'
      
            
  #     lamd: 0.00001
  #     batch_size: 32
  # - key: 'CosineLoss'
  #   kwargs:
  #     student_module_path: 'LL'
  #     student_module_io: 'output'
  #     teacher_module_path: 'LL'
  #     teacher_module_io: 'output'

  # - key: 'MSELoss'
  #   kwargs:
  #     student_module_path: 'LL'
  #     student_module_io: 'output'
  #     teacher_module_path: 'LL'
  #     teacher_module_io: 'output'
